### PR TITLE
Add options to the readme.

### PR DESCRIPTION
**Pull request by danielhusar**
Feel free to change it if you dont like the structure :)

### CODE REVIEW

**Comment by matiassingers** [comment]
@danielhusar thanks so much!

I like it!

----
Couple of small things:
- [ ] Squash all commits
- [ ] API in all capitals
- [ ] Ensure new line after the type, like so (a couple of blank spaces): 
```md
Type: `number` *(seconds)*  
Default: `0`
```

**Comment by danielhusar** [comment]
Hey :)

Thanks, I have capitalised that API.
But I'm not sure what you mean by ensuring new line after the type, as there is already a new line.

**Comment by matiassingers** [comment]
@danielhusar my bad, didn't explain it very well.

Just add two blank spaces after the type to make sure the default goes on a new line, but in the same paragraph as the type.

**Comment by danielhusar** [comment]
Oh right, done. (I didn't know about that trick :) )

**Comment by matiassingers** [comment]
@danielhusar perfect!

Merging, and again thanks so much! :+1:

**Comment by danielhusar** [comment]
Cool, cheers.

**Comment by matiassingers** [comment]
Published to npm as [0.5.0](https://github.com/matiassingers/generator-simple-node-package/releases/tag/0.5.0).

**Pull request merged**
